# Generated by Django 3.0.6 on 2020-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(default='static/default.jpg', upload_to='images/'),
        ),
    ]
